<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		$('#artist-list').dataTable({
"sAjaxSource": "<?php echo $this->url(array('controller' => 'artist', 'action' => 'listjson'), 'default') ?>",
			"bProcessing": true,
			"sProcessing": true,
			"aoColumns": [
				{ "bVisible": false },
				null
			],
			"aaSorting": [[1, "asc"]],
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
			"aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
			"fnRowCallback": function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
				$('td:eq(0)', nRow).html( '<a href="/artist/' + aData[0] + '">' + aData[1] + '</a><span class="right"><a href="/artist/edit/' + aData[0] + '"><img src="/images/edit.gif" /></a></span>' );
				return nRow;
			}

		});
	} );
</script>
<table id="artist-list" class="content-list">
  <thead>
	<tr><th>id</th><th>Name</th></tr>
  </thead>
  <tbody>
  </tbody>
</table>

