<?php 
if (isset($this->flag) && isset($this->search)) {
	$ajaxSource = $this->url(array('controller' => 'anime', 'action' => 'listjson', 'flag' => $this->flag, 'search' => $this->search), 'default');
}
else {
	$ajaxSource = $this->url(array('controller' => 'anime', 'action' => 'listjson'), 'default');
}
?>
<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		$('#anime-list').dataTable({
			"sAjaxSource": "<?php echo $ajaxSource ?>",
			"bProcessing": true,
			"sProcessing": true,
			"aoColumns": [
				{ "bVisible": false },
				null
			],
			"aaSorting": [[1, "asc"]],
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
			"aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
			"fnRowCallback": function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
				$('td:eq(0)', nRow).html( '<a href="/anime/' + aData[0] + '">' + aData[1] + '</a><span class="right"><a href="/anime/edit/' + aData[0] + '"><img src="/images/edit.gif" /></a></span>' );
				return nRow;
			}

		});
	} );
</script>
<table id="anime-list" class="content-list">
  <thead>
	<tr><th>id</th><th>Name</th></tr>
  </thead>
  <tbody>
  </tbody>
</table>
