<?php
function formatDuration($duration) {
	if ($duration < 60) {
		echo $duration . ' seconds';
	} else if ($duration < 3600) {
		$minutes = floor($duration / 60);
		$seconds = $duration - ($minutes * 60);
		echo $minutes . ' minutes, ' . $seconds . ' seconds';
	} else {
		$hours =  floor($duration / 3600);
		$minutes = floor(($duration - ($hours * 3600)) / 60);
		$seconds = $duration - ($hours * 3600) - ($minutes * 60);
		echo $hours . ' hours, ' . $minutes . ' minutes, ' . $seconds . ' seconds';
	}
}
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script src="http://www.highcharts.com/js/highcharts.js" type="text/javascript"></script>
<script type="text/javascript">
var chart, chart2;
$(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
         renderTo: 'subtypes',
         plotBackgroundColor: null,
         plotBorderWidth: null,
         plotShadow: false
      },
      title: {
         text: 'Shares by subtitle type'
      },
      tooltip: {
         formatter: function() {
            return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
         }
      },
      plotOptions: {
         pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
               enabled: true,
               color: '#000000',
               connectorColor: '#000000',
               formatter: function() {
                  return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
               }
            }
         }
      },
       series: [{
         type: 'pie',
         name: 'SubType share',
         data: [
            ['ass1', <?php echo 100 * round($this->ass1 / $this->karaCount, 3);?>],
            {
               name: 'ass2',    
               y: <?php echo 100 * round($this->ass2 / $this->karaCount, 3); ?>,
               sliced: true,
               selected: true
            },
            ['srt', <?php echo 100 * round($this->srt / $this->karaCount, 3); ?>],
            ['incrusted', <?php echo 100 * round($this->incrusted / $this->karaCount, 3); ?>],
            ['voiceless', <?php echo 100 * round($this->voiceless / $this->karaCount, 3); ?>]
         ]
      }]
  });
  chart2 = new Highcharts.Chart({
      chart: {
         renderTo: 'sourcetypes',
         plotBackgroundColor: null,
         plotBorderWidth: null,
         plotShadow: false
      },
      title: {
         text: 'Shares by source type'
      },
      tooltip: {
         formatter: function() {
            return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
         }
      },
      plotOptions: {
         pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
               enabled: true,
               color: '#000000',
               connectorColor: '#000000',
               formatter: function() {
                  return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
               }
            }
         }
      },
       series: [{
         type: 'pie',
         name: 'SubType share',
         data: [
            ['movie', <?php echo 100 * round($this->movie / $this->karaCount, 3);?>],
            {
               name: 'anime',    
               y: <?php echo 100 * round($this->anime / $this->karaCount, 3); ?>,
               sliced: true,
               selected: true
            },
            ['show', <?php echo 100 * round($this->show / $this->karaCount, 3); ?>],
            ['game', <?php echo 100 * round($this->game / $this->karaCount, 3); ?>],
            ['misc', <?php echo 100 * round($this->misc / $this->karaCount, 3); ?>],
            ['artist', <?php echo 100 * round($this->artist / $this->karaCount, 3); ?>]
         ]
      }]
   });
});
</script>
<style>
.label { width: 120px; display: inline-block; }
.container { float: right; }
</style>
<div style="float: left; min-width: 450px;">
<h1>Total number of karaoke : <?php echo $this->karaCount; ?></h1>
&nbsp;&nbsp;&nbsp;&nbsp;<?php echo formatDuration($this->karaDuration); ?>
<h1>Karaoke by subtitle type</h1>
<ul>
    <li><span class="label">ASS1 : <?php echo $this->ass1; ?></span> (<?php echo formatDuration($this->ass1Duration); ?>)</li>
    <li><span class="label">ASS2 : <?php echo $this->ass2; ?></span> (<?php echo formatDuration($this->ass2Duration); ?>)</li>
    <li><span class="label">SRT : <?php echo $this->srt; ?></span> (<?php echo formatDuration($this->srtDuration); ?>)</li>
    <li><span class="label">incrusted : <?php echo $this->incrusted; ?></span> (<?php echo formatDuration($this->incrustedDuration); ?>)</li>
    <li><span class="label">voiceless : <?php echo $this->voiceless; ?></span> (<?php echo formatDuration($this->voicelessDuration); ?>)</li>
</ul>
<h1>Karaoke by source type</h1>
<ul>
    <li><span class="label">Anime : <?php echo $this->anime; ?></span> (<?php echo formatDuration($this->animeDuration); ?>)</li>
    <li><span class="label">TV Show : <?php echo $this->show; ?></span> (<?php echo formatDuration($this->showDuration); ?>)</li>
    <li><span class="label">Movie : <?php echo $this->movie; ?></span> (<?php echo formatDuration($this->movieDuration); ?>)</li>
    <li><span class="label">Game : <?php echo $this->game; ?></span> (<?php echo formatDuration($this->gameDuration); ?>)</li>
    <li><span class="label">Misc : <?php echo $this->misc; ?></span> (<?php echo formatDuration($this->miscDuration); ?>)</li>
    <li><span class="label">Artist : <?php echo $this->artist; ?></span> (<?php echo formatDuration($this->artistDuration); ?>)</li>
</ul>
<h1>Karaoke by author</h1>
<ul>
    <?php foreach($this->authors as $author => $nb) : ?>
	<li><?php echo $author; ?> : <?php echo $nb; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<div id="subtypes" class="container"></div>
<div id="sourcetypes" class="container"></div>
